//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace ModisDownloader.Xsd
{
}

// 
// 此源代码由 xsd 自动生成, Version=4.6.1055.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://modapsws.gsfc.nasa.gov/xsd", IsNullable=false)]
public partial class getFilePropertiesResponse {
    
    private getFilePropertiesResponseReturn[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public getFilePropertiesResponseReturn[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class getFilePropertiesResponseReturn {
    
    private string checksumField;
    
    private string fileIdField;
    
    private string fileNameField;
    
    private string fileSizeBytesField;
    
    private string fileTypeField;
    
    private string ingestTimeField;
    
    private string onlineField;
    
    private string startTimeField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
    public string checksum {
        get {
            return this.checksumField;
        }
        set {
            this.checksumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
    public string fileId {
        get {
            return this.fileIdField;
        }
        set {
            this.fileIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
    public string fileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
    public string fileSizeBytes {
        get {
            return this.fileSizeBytesField;
        }
        set {
            this.fileSizeBytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
    public string fileType {
        get {
            return this.fileTypeField;
        }
        set {
            this.fileTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
    public string ingestTime {
        get {
            return this.ingestTimeField;
        }
        set {
            this.ingestTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
    public string online {
        get {
            return this.onlineField;
        }
        set {
            this.onlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
    public string startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://modapsws.gsfc.nasa.gov/xsd")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}
